# Generated by Django 6.0.5 on 2026-05-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLIENT_REMINDER', 'Recordatorio para cliente'), ('STAFF_REMINDER', 'Recordatorio para esteticista')], default='CLIENT_REMINDER', max_length=30, verbose_name='Tipo de notificación'),
            preserve_default=False,
        ),
    ]
